name: Build and Release

on:
  push:
    branches:
      - main
    paths:
      - package.json
      - src/**
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # タグ操作には全履歴が必要
      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      - name: get version
        id: get_version
        run: |
          echo "VERSION=v$(jq -r .version package.json)" >> $GITHUB_ENV
      - name: Create or move tag
        run: |
          git tag -fa ${{ env.VERSION }} -m "Move tag to latest commit"
          git push origin ${{ env.VERSION  }} --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: create tag
        run: |
      
  build-and-release:
    runs-on: ${{ matrix.os }}
    needs: tag
    strategy:
      matrix:
        include:
          - os: windows-latest
            build_cmd: npm run build-win64
          - os: windows-latest
            build_cmd: npm run build-win32
          - os: macos-latest
            build_cmd: npm run build-mac

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build and release binaries
        run: ${{ matrix.build_cmd }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
