name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            build_cmd: npm run build-win64
            artifact_suffix: _win64.exe
            src: build/win-unpacked/soracom-button Setup.exe
          - os: windows-latest
            build_cmd: npm run build-win32
            artifact_suffix: _win32.exe
            src: build/win-ia32-unpacked/soracom-button Setup.exe
          - os: macos-latest
            build_cmd: npm run build-mac
            artifact_suffix: .dmg
            src: build/mac/*.dmg

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Get version
        id: version
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Build
        run: npm run build

      - name: Build release binaries
        run: ${{ matrix.build_cmd }}

      - name: Set artifact name
        id: set_artifact_name
        run: echo "artifact_name=soracom-button-Setup-${{ steps.version.outputs.version }}${{ matrix.artifact_suffix }}" >> $GITHUB_ENV

      - name: Rename files
        run: |
          mkdir -p dist
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            src_file=$(ls build/mac/*.dmg | head -n 1)
          else
            src_file="${{ matrix.src }}"
          cp "$src_file" "dist/${{ env.artifact_name }}"
          cp "$src_file" "dist/${{ matrix.rename }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}
          path: |
            dist/${{ env.artifact_name }}
            dist/${{ matrix.rename }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/soracom-button-Setup-*.exe
            dist/soracom-button-Setup-*.dmg
